blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('tag/<str:tag_slug>/', views.post_list, name='tag_post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/', views.post_share, name='share_post'),
    path('add_comment/<int:post_id>/', views.add_comment, name='add_comment'),
    path('search/', views.post_search, name='post_search')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from blog.sitemaps import PostSitemap
from django.contrib.sitemaps.views import sitemap
from django.conf import settings
from django.conf.urls.static import static

sitemaps = {'posts': PostSitemap}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('oauth/', include('social_django.urls', namespace='social')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager


class Published(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='PB')


class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = ('DF', 'Черновик')
        PUBLISHED = ('PB', 'Опубликовано')

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    body = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    publish = models.DateTimeField(auto_now_add=True)
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.DRAFT)

    objects = models.Manager()
    published = Published()
    tags = TaggableManager()

    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish']),
        ]

    def __str__(self):
        return self.title[:50]

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[
                           self.publish.year,
                           self.publish.month,
                           self.publish.day,
                           self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    body = models.TextField()
    create = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['-create']
        indexes = [models.Index(fields=['create'])]

    def __str__(self):
        return f'Комментарий пользователя {self.name} от {self.create}'

blog/forms.py
from django import forms
from .models import Post, Comment
from django.conf import settings


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=30,
                           widget=forms.TextInput(attrs={"class": "form-control mb-1", 'placeholder': 'Имя'}))
    email_from = forms.EmailField(initial=settings.EMAIL_HOST_USER,
                                  widget=forms.TextInput(attrs={"class": "form-control mb-1"}))
    email_to = forms.EmailField(
        widget=forms.TextInput(attrs={"class": "form-control mb-1", 'placeholder': 'E-mail получателя'}))
    comment = forms.CharField(required=False,
                              widget=forms.Textarea(attrs={"class": "form-control mb-1", 'placeholder': 'Комментарий'}))


class CommentPostForm(forms.ModelForm):
    name = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class': 'form-control',
                                                                        'placeholder': 'Ваше имя'}))
    body = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control',
                                                        'placeholder': 'Ваш комментарий'}))

    class Meta:
        model = Comment
        fields = ['name', 'body']


class SearchForm(forms.Form):
    query = forms.CharField(max_length=50, label='Введите запрос',
                            required=False,
                            widget=forms.TextInput(
                                attrs={"class": "form-control mb-1", 'placeholder': 'Ввод запроса...'})
                            )

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import EmailPostForm, CommentPostForm, SearchForm
from .models import Post, Comment
from taggit.models import Tag
from django.db.models import Count
from django.http import HttpResponse, HttpResponseRedirect
from django.core.mail import send_mail
from django.conf import settings
from django.views.decorators.http import require_POST
from django.contrib.postgres.search import SearchVector, SearchRank, SearchQuery


# Create your views here.
def post_list(request, tag_slug=None):
    if tag_slug:
        tag = Tag.objects.get(slug=tag_slug)
        post_list = Post.objects.filter(tags=tag)
    else:
        post_list = Post.published.all()
    paginator = Paginator(post_list, 2)
    page = request.GET.get('page', 1)
    try:
        posts_for_page = paginator.page(page)
    except EmptyPage:
        posts_for_page = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        posts_for_page = paginator.page(1)
    return render(request, 'blog/post/list.html', context={'posts': posts_for_page})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, publish__year=year, publish__month=month, publish__day=day, slug=post)
    tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.objects.filter(tags__in=tags_ids).exclude(id=post.id) \
        .annotate(same_tags=Count('tags'))
    # print(similar_posts.query)
    similar_posts = similar_posts.order_by('-same_tags', '-publish')
    comments = Comment.objects.filter(post=post, active=True)
    comment_form = CommentPostForm()
    if request.user.is_authenticated:
        comment_form = CommentPostForm({'name': request.user.username})
    return render(request, 'blog/post/detail.html',
                  context={'post': post, 'form': comment_form, 'comments': comments, 'similar_posts': similar_posts})


def post_share(request, post_id):
    post = get_object_or_404(Post, pk=post_id, status=Post.Status.PUBLISHED)
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            send_mail(f'{data["name"]} рекомендует вам почитать {post.title}',
                      f'Ссылка: {request.build_absolute_uri(post.get_absolute_url())}\nКомментарий: {data["comment"]}',
                      settings.EMAIL_HOST_USER,
                      [data['email_to']],
                      )
            return HttpResponse(
                f'<h2>Сообщение отправлено успешно</h2><br><a href="{post.get_absolute_url()}">К списку постов</a>')
    else:
        form = EmailPostForm()
        return render(request, 'blog/post/share.html', context={'form': form, 'post': post})


@require_POST
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id, status=Post.Status.PUBLISHED)
    form = CommentPostForm(data=request.POST)
    comment = None
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
    return render(request, 'blog/post/includes/comment.html', context={'form': form, 'comment': comment, 'post': post})


def post_search(request):
    form = SearchForm()
    query = None
    result = []
    if request.method == 'GET':
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = SearchVector('title', 'body', config='russian')
            search_query = SearchQuery(query, config='russian')
            result = (Post.published.
                      annotate(search=search_vector, rang=SearchRank(search_vector, search_query)).
                      filter(search=query).order_by('-rang'))
    return render(request, 'blog/post/search.html', context={'form': form,
                                                             'query': query,
                                                             'results': result})

templates/blog/base.html
{% load static %}
{% load blog_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Блог{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    {% load django_bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="/blog/">Мой блог на Django</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span
                    class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'users-profile' %}"><img
                                class="rounded-circle" width="30" src="{{ user.profile.avatar.url }}"/> {{ user.username }}
                        </a></li>
                        <li class="nav-item">
                            <form method="post" action="{% url 'logout' %}">
                                {% csrf_token %}
                                <a class="nav-link" href="#" onclick="parentNode.submit();">Выйти</a>
                            </form>
                        </li>
                    {% else %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Войти</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'signup' %}">Регистрация</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <div class="container mt-5">
        <div class="row">
            <div class="col-lg-8">
                {% if messages %}
                    {% for message in messages %}
                        <div class="container d-flex align-items-center justify-content-center">
                            <div class="alert alert-warning alert-dismissible fade show w-50  d-block" role="alert">
                                {{ message }}
                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            </div>
                        </div>
                    {% endfor %}
                {% endif %}
                {% block content %}{%endblock%}
            </div>
            <div class="col-lg-4">
                <div class="card mb-4">
                    <div class="card-header">Это веб-приложение блог</div>
                    <div class="card-body">Всего публикаций: {% total_posts %}</div>
                </div>
                <div class="card mb-4">
                    <div class="card-header">Поиск</div>
                    <div class="card-body">
                        <div class="input-group">
                            <form action="{% url 'blog:post_search' %}" method="get" class="input-group">
                                <input type="text" name="query" class="form-control" placeholder="Введите запрос..."
                                       required="" id="id_query">
                                <button class="btn btn-primary" id="button-search" type="submit">Искать!</button>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="card mb-4">
                    <div class="list-group">
                        <a class="list-group-item list-group-item-action active" aria-current="true">
                            Последние публикации
                        </a>
                        {% latest_posts 3 %}
                    </div>
                </div>
                <div class="card mb-4">
                    <div class="list-group">
                        <a class="list-group-item list-group-item-action active" aria-current="true">
                            Самое комментируемое
                        </a>
                        {% get_most_commented_posts as most_commented_posts %}
                        {% for post in most_commented_posts %}
                            <a class="list-group-item list-group-item-action" href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <footer class="py-5 bg-dark mt-2">
        <div class="container"><p class="m-0 text-center text-white">Copyright &copy; MyBlog 2025, Powered by
            Django</p></div>
    </footer>
</body>
</html>