blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('tag/<str:tag_slug>/', views.post_list, name='tag_post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/', views.post_share, name='share_post'),
    path('add_comment/<int:post_id>/', views.add_comment, name='add_comment'),
    path('search/', views.post_search, name='post_search')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from blog.sitemaps import PostSitemap
from django.contrib.sitemaps.views import sitemap
from django.conf import settings
from django.conf.urls.static import static

sitemaps = {'posts': PostSitemap}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('oauth/', include('social_django.urls', namespace='social')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager


class Published(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='PB')


class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = ('DF', 'Черновик')
        PUBLISHED = ('PB', 'Опубликовано')

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    body = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    publish = models.DateTimeField(auto_now_add=True)
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.DRAFT)

    objects = models.Manager()
    published = Published()
    tags = TaggableManager()

    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish']),
        ]

    def __str__(self):
        return self.title[:50]

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[
                           self.publish.year,
                           self.publish.month,
                           self.publish.day,
                           self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    body = models.TextField()
    create = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['-create']
        indexes = [models.Index(fields=['create'])]

    def __str__(self):
        return f'Комментарий пользователя {self.name} от {self.create}'

blog/forms.py
from django import forms
from .models import Post, Comment
from django.conf import settings


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=30,
                           widget=forms.TextInput(attrs={"class": "form-control mb-1", 'placeholder': 'Имя'}))
    email_from = forms.EmailField(initial=settings.EMAIL_HOST_USER,
                                  widget=forms.TextInput(attrs={"class": "form-control mb-1"}))
    email_to = forms.EmailField(
        widget=forms.TextInput(attrs={"class": "form-control mb-1", 'placeholder': 'E-mail получателя'}))
    comment = forms.CharField(required=False,
                              widget=forms.Textarea(attrs={"class": "form-control mb-1", 'placeholder': 'Комментарий'}))


class CommentPostForm(forms.ModelForm):
    name = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class': 'form-control',
                                                                        'placeholder': 'Ваше имя'}))
    body = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control',
                                                        'placeholder': 'Ваш комментарий'}))

    class Meta:
        model = Comment
        fields = ['name', 'body']


class SearchForm(forms.Form):
    query = forms.CharField(max_length=50, label='Введите запрос',
                            required=False,
                            widget=forms.TextInput(
                                attrs={"class": "form-control mb-1", 'placeholder': 'Ввод запроса...'})
                            )

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import EmailPostForm, CommentPostForm, SearchForm
from .models import Post, Comment
from taggit.models import Tag
from django.db.models import Count
from django.http import HttpResponse, HttpResponseRedirect
from django.core.mail import send_mail
from django.conf import settings
from django.views.decorators.http import require_POST
from django.contrib.postgres.search import SearchVector, SearchRank, SearchQuery


# Create your views here.
def post_list(request, tag_slug=None):
    if tag_slug:
        tag = Tag.objects.get(slug=tag_slug)
        post_list = Post.objects.filter(tags=tag)
    else:
        post_list = Post.published.all()
    paginator = Paginator(post_list, 2)
    page = request.GET.get('page', 1)
    try:
        posts_for_page = paginator.page(page)
    except EmptyPage:
        posts_for_page = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        posts_for_page = paginator.page(1)
    return render(request, 'blog/post/list.html', context={'posts': posts_for_page})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, publish__year=year, publish__month=month, publish__day=day, slug=post)
    tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.objects.filter(tags__in=tags_ids).exclude(id=post.id) \
        .annotate(same_tags=Count('tags'))
    # print(similar_posts.query)
    similar_posts = similar_posts.order_by('-same_tags', '-publish')
    comments = Comment.objects.filter(post=post, active=True)
    comment_form = CommentPostForm()
    if request.user.is_authenticated:
        comment_form = CommentPostForm({'name': request.user.username})
    return render(request, 'blog/post/detail.html',
                  context={'post': post, 'form': comment_form, 'comments': comments, 'similar_posts': similar_posts})


def post_share(request, post_id):
    post = get_object_or_404(Post, pk=post_id, status=Post.Status.PUBLISHED)
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            send_mail(f'{data["name"]} рекомендует вам почитать {post.title}',
                      f'Ссылка: {request.build_absolute_uri(post.get_absolute_url())}\nКомментарий: {data["comment"]}',
                      settings.EMAIL_HOST_USER,
                      [data['email_to']],
                      )
            return HttpResponse(
                f'<h2>Сообщение отправлено успешно</h2><br><a href="{post.get_absolute_url()}">К списку постов</a>')
    else:
        form = EmailPostForm()
        return render(request, 'blog/post/share.html', context={'form': form, 'post': post})


@require_POST
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id, status=Post.Status.PUBLISHED)
    form = CommentPostForm(data=request.POST)
    comment = None
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
    return render(request, 'blog/post/includes/comment.html', context={'form': form, 'comment': comment, 'post': post})


def post_search(request):
    form = SearchForm()
    query = None
    result = []
    if request.method == 'GET':
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = SearchVector('title', 'body', config='russian')
            search_query = SearchQuery(query, config='russian')
            result = (Post.published.
                      annotate(search=search_vector, rang=SearchRank(search_vector, search_query)).
                      filter(search=query).order_by('-rang'))
    return render(request, 'blog/post/search.html', context={'form': form,
                                                             'query': query,
                                                             'results': result})

templates/blog/post/detail.html
{% extends 'blog/base.html' %}
{% load blog_tags %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
    <h1 class="fw-bolder">Пост "{{ post.title }}" пользователя {{ post.author }}</h1>
    <p class="text-muted fst-italic mb-2 text-start">Опубликовано {{post.publish}} пользователем {{ post.author }}</p>
    {{ post.body|markdown }}
    <a href="{% url 'blog:share_post' post.id %}" class="btn btn-primary float-left">Рекомендовать пост</a><br>
    <br>
    <a href="{% url 'blog:post_list' %}">К списку постов</a>
    {% if similar_posts %}
        <div class="row card mt-2">
            <h2>Похожие посты</h2>
            {% for similar_post in similar_posts %}
                <p><a href="{{ similar_post.get_absolute_url }}">{{ similar_post.title }} {{similar_post.same_tags }}</a></p>
            {% endfor %}
        </div>
    {% endif %}
    <div class="row card mt-2">
        {% include 'blog/post/includes/add_comment_form.html' %}
        {% with comments.count as total_comments %}
            <h2>Комментариев {{total_comments}}</h2>
        {% endwith %}
        <br>
        {% for comment in comments %}
            <div class="comment">
                <p class="info">Комментарий {{ forloop.counter }} от {{comment.name }} {{comment.create}}</p>
                {{ comment.body }}</div>
        {% empty %}
            <p>Нет комментариев</p>
        {% endfor %}
    </div>
{% endblock %}

templates/blog/post/lates_posts.html
<ul>
    {% for post in latest_posts %}
        <li><a href="{{post.get_absolute_url}}">{{post.title}}</a></li>
    {% endfor %}
</ul>

templates/blog/post/latest_posts.html
{% for post in latest_posts %}
    <a class="list-group-item list-group-item-action" href="{{post.get_absolute_url}}">{{post.title}}</a>
{% endfor %}

templates/blog/post/list.html
{% extends 'blog/base.html' %}
{% load blog_tags %}
{% block content %}
    {% for post in posts %}
        <div>
            <h2 class="fw-bolder">
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </h2>
            <p class="tag">
                {% if post.tags.all %}
                    Теги:
                    {% for tag in post.tags.all %}
                        <a href="{% url 'blog:tag_post_list' tag.slug %}" class="badge bg-secondary text-decoration-none link-light">
                            {{ tag.name }}
                        </a>
                    {% endfor %}
                {% else %}Теги: нет тегов (пока)
                {% endif %}
                <p class="date">Опубликовано {{post.publish}} пользователем {{ post.author }}</p>
                {{ post.body|markdown|truncatewords:30 }}
            </p>
        </div>
    {% endfor %}
    {% include 'blog/post/paginator.html' with page=posts%}
{% endblock %}

templates/blog/post/paginator.html
<div class="pagination p-3">
    {% if page.has_previous %}
        <a href="?page={{page.previous_page_number}}" class="page-link">Предыдущая</a>
    {% endif %}
    {% for num_page in page.paginator.page_range %}
        {% if num_page == page.number %}
            <a href="?page={{num_page}}" class="page-link disabled">{{ num_page }}</a>
        {% else %}
            <a href="?page={{num_page }}" class="page-link">{{ num_page }}</a>
        {% endif %}
    {% endfor %}
    {% if page.has_next %}
        <a href="?page={{page.next_page_number}}" class="page-link">Следующая</a>
    {% endif %}
</div>

templates/blog/post/search.html
{% extends 'blog/base.html' %}
{% block title %}Поиск{% endblock %}
{% block content %}
    {% if query %}
        <h2>Результаты поиска по запросу "{{ query }}"</h2>
        <h3>{% with results.count as total_results %}Найдено {{ total_results }} результатов:{% endwith %}</h3>
        <ul>
            {% for post in results %}
                <li><a href="{{post.get_absolute_url}}">{{post.title}}</a></li>
            {% empty %}
                <h2>Результатов по запросу "{{ query }}" не найдено</h2>
            {% endfor %}
        </ul>
        <a href="{% url 'blog:post_search' %}">Искать снова</a>
    {% else %}
        <h1>Поиск публикаций</h1>
        <form method="get" action="">
            <div>
                {% csrf_token %}<br>
                {{ form.query }}<br>
                <input type="submit" value="Найти" class="btn btn-primary mb-3 btn-lg">
            </div>
        </form>
    {% endif %}
    <p><a href="{% url 'blog:post_list' %}">На главную</a></p>
{% endblock %}

templates/blog/post/share.html
{% extends 'blog/base.html' %}
{% block title %}Рекомендуем пост {% endblock %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary mb-3 btn-lg">Отправить</button>
    </form>
{% endblock %}