blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('tag/<str:tag_slug>/', views.post_list, name='tag_post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/', views.post_share, name='share_post'),
    path('add_comment/<int:post_id>/', views.add_comment, name='add_comment'),
    path('search/', views.post_search, name='post_search')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from blog.sitemaps import PostSitemap
from django.contrib.sitemaps.views import sitemap
from django.conf import settings
from django.conf.urls.static import static

sitemaps = {'posts': PostSitemap}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('oauth/', include('social_django.urls', namespace='social')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/blog/post/includes/add_comment_form.html
<h2>Добавить комментарий:</h2>
<form method="post" action="{% url 'blog:add_comment' post.id %}">
    {% csrf_token %}
    <div class="row">
        <div class="col mt-2">{{ form.name }}</div>
        <div class="mt-2">
            {{ form.body }}
            <input class="btn btn-primary mb-3" type="submit" value="Добавить комментарий">
        </div>
    </div>
</form>

templates/blog/post/includes/comment.html
{% if comment %}
    <h2>Комментарий успешно добавлен</h2>
    <a href="{{post.get_absolute_url}}">Назад к посту</a>
{% else %}
    {% include 'blog/post/includes/add_comment_form.html' %}
{% endif %}